name: Gitleaks Scan

on: [push]

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Install Gitleaks
      run: |
        curl -sSL https://github.com/zricethezav/gitleaks/releases/download/v8.2.2/gitleaks_8.2.2_linux_x64.tar.gz | tar -xz
        sudo mv gitleaks /usr/local/bin/

    - name: Run Gitleaks
      run: |
        gitleaks detect --source . --config=gitleaks.toml --verbose
